; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny202]
platform = atmelmegaavr
board = ATtiny202
framework = arduino
board_build.f_cpu = 16000000L
upload_protocol = serialupdi
upload_speed = 57600

; Automatic detection or manual port selection (uncomment if needed)
; upload_port = /dev/ttyUSB0

[env:brake_indicator]
extends = env:ATtiny202
src_filter = +<brake_indicator.c> -<blink_test.c>

[env:blink_test]
extends = env:ATtiny202
src_filter = +<blink_test.c> -<brake_indicator.c>
